development:
  adapter: postgresql
  encoding: unicode
  database: wherecode_development
  pool: 5
  username: wherecode
  password: t7he3p49
test:
  adapter: postgresql
  encoding: unicode
  database: wherecode_test
  pool: 5
  username: wherecode
  password: t7he3p49
production:
  adapter: postgresql
  encoding: unicode
  database: wherecode_production
  pool: 5
  username: wherecode
  password: t7he3p49